version: 2

test:
  docker:
    - image: circleci/python:3.7
  steps:
    - checkout
    - run: git submodule update --init

    - run: pipenv install

    - run: make html
    - run: make publish

deploy:
  docker:
    - image: circleci/python:3.7
  steps:
    - checkout
    - run: git submodule update --init

    - run: |
        git config user.name "release-bot"
        git config user.email "release-bot@users.noreply.github.com"
        git remote set-url origin \
          "https://${GITHUB_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"

    - run: make github

workflows:
  version: 2

  test:
    jobs:
      - test:
        filters:
          branches:
            ignore: gh-pages

  build-and-deploy:
    jobs:
      - deploy:
        filters:
          branches:
            only: master
