version: 2

jobs:
  test:
    docker:
      - image: circleci/python:3.7-node
    steps:
      - checkout
      - run: git submodule update --init

      - run: |
          sudo update-locale LANG=C.UTF-8 LC_MESSAGES=POSIX
          DEBIAN_FRONTEND=noninteractive sudo -E dpkg-reconfigure locales

      - run: |
          [[ ! -d /usr/local/bin ]] || \
            sudo chown -R circleci:circleci /usr/local/bin
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: deps9-{{ .Branch }}-{{ checksum "poetry.lock" }}-{{ checksum "package-lock.json" }}-v5
      - run: |
          sudo pip install --upgrade pip
          sudo pip install poetry
          poetry install
          npm install
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "poetry.lock" }}-{{ checksum "package-lock.json" }}-v5
          paths:
            - ".poetry"
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
            - "./node_modules"

      - run: make html
      - run: make publish

  deploy:
    docker:
      - image: circleci/python:3.7-node
    steps:
      - checkout
      - run: git submodule update --init

      - run: |
          sudo update-locale LANG=C.UTF-8 LC_MESSAGES=POSIX
          DEBIAN_FRONTEND=noninteractive sudo -E dpkg-reconfigure locales

      - run: |
          [[ ! -d /usr/local/bin ]] || \
            sudo chown -R circleci:circleci /usr/local/bin
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: deps9-{{ .Branch }}-{{ checksum "poetry.lock" }}-{{ checksum "package-lock.json" }}-v5
      - run: |
          sudo pip install --upgrade pip
          sudo pip install poetry
          poetry install
          npm install

      - run: |
          git config user.name "release-bot"
          git config user.email "release-bot@users.noreply.github.com"
          git remote set-url origin \
            "https://${GITHUB_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"
          make github

workflows:
  version: 2

  test:
    jobs:
      - test:
          filters:
            branches:
              ignore: gh-pages

  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
