version: 2

jobs:
  test:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - checkout
      - run: git submodule update --init

      - run: |
          sudo sed -i 's/ja_JP\s.*$/ja_JP ja_JP.utf8/g' /usr/share/locale/locale.alias
          sudo sed -i 's/# ja_JP\.UTF-8/ja_JP\.UTF-8/' /etc/locale.gen
          sudo update-locale LANG=C.UTF-8 LC_MESSAGES=POSIX
          DEBIAN_FRONTEND=noninteractive sudo -E dpkg-reconfigure locales

      - run: |
          [[ ! -d /usr/local/bin ]] || \
            sudo chown -R circleci:circleci /usr/local/bin
          [[ ! -d /usr/local/lib/python3.6/site-packages ]] || \
            sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}-v1
      - run: |
          sudo pip install --upgrade pip
          sudo pip install pipenv
          pipenv install
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}-v1
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
            - "/var/lib/apt/lists"

      - run: make html
      - run: make publish

  deploy:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - checkout
      - run: git submodule update --init

      - run: |
          sudo sed -i 's/ja_JP\s.*$/ja_JP ja_JP.utf8/g' /usr/share/locale/locale.alias
          sudo sed -i 's/# ja_JP\.UTF-8/ja_JP\.UTF-8/' /etc/locale.gen
          sudo update-locale LANG=C.UTF-8 LC_MESSAGES=POSIX
          DEBIAN_FRONTEND=noninteractive sudo -E dpkg-reconfigure locales

      - run: |
          [[ ! -d /usr/local/bin ]] || \
            sudo chown -R circleci:circleci /usr/local/bin
          [[ ! -d /usr/local/lib/python3.6/site-packages ]] || \
            sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}-v1
      - run: |
          sudo pip install --upgrade pip
          sudo pip install pipenv
          pipenv install

      - run: |
          git config user.name "release-bot"
          git config user.email "release-bot@users.noreply.github.com"
          git remote set-url origin \
            "https://${GITHUB_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"
          make github

workflows:
  version: 2

  test:
    jobs:
      - test:
          filters:
            branches:
              ignore: gh-pages

  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
