name: 'Setup Development Environment'
description: 'Setup Nix, devenv, and install dependencies'
inputs:
  with-locale:
    description: 'Enable Japanese locale setup'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Enable ja_JP.UTF-8 locale
      if: ${{ inputs.with-locale == 'true' }}
      shell: bash
      run: |
        sudo sed -i 's/# ja_JP\.UTF-8/ja_JP\.UTF-8/' /etc/locale.gen
        sudo update-locale LANG=C.UTF-8 LC_MESSAGES=POSIX
        DEBIAN_FRONTEND=noninteractive sudo -E dpkg-reconfigure locales
    - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31.9.0
    - uses: cachix/cachix-action@3ba601ff5bbb07c7220846facfa2cd81eeee15a1 # v16
      with:
        name: devenv
    - name: Cache uv
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        key: uv1-${{ runner.os }}-${{ hashFiles('**/uv.lock') }}
        path: |
          ~/.cache/uv
          .venv
    - name: Cache npm
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        key: npm1-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        path: |
          ~/.npm
          node_modules
    - name: Install by devenv
      shell: bash
      run: |
        nix profile install nixpkgs#devenv
        devenv shell echo
    - name: Install Python packages
      shell: bash
      run: devenv shell uv sync
    - name: Install npm packages
      shell: bash
      run: devenv shell npm ci
