name: CI Build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Enable ja_JP.UTF-8 locale
      run: |
        sudo sed -i 's/# ja_JP\.UTF-8/ja_JP\.UTF-8/' /etc/locale.gen
        sudo update-locale LANG=C.UTF-8 LC_MESSAGES=POSIX
        DEBIAN_FRONTEND=noninteractive sudo -E dpkg-reconfigure locales

    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Cache poetry
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-v1
        path: |
          ~/.poetry
          .venv

    - name: Cache npm
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-v1
        path: |
          ~/.npm
          node_modules

    - name: Install poetry
      run: |
        pip install poetry
        poetry config virtualenvs.in-project true
    - name: Install poetry dependencies
      run: poetry install

    - name: Install npm dependencies
      run: npm ci

    - name: Build
      run: |
        make html
        make publish
