name: Deploy GitHub Pages

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-22.04

    permissions:
      pages: write
      id-token: write

    steps:
    - name: Enable ja_JP.UTF-8 locale
      run: |
        sudo sed -i 's/# ja_JP\.UTF-8/ja_JP\.UTF-8/' /etc/locale.gen
        sudo update-locale LANG=C.UTF-8 LC_MESSAGES=POSIX
        DEBIAN_FRONTEND=noninteractive sudo -E dpkg-reconfigure locales

    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install stork
      run: |
        sudo wget -O /usr/local/bin/stork https://files.stork-search.net/releases/v1.6.0/stork-ubuntu-22-04
        sudo chmod +x /usr/local/bin/stork

    - name: Cache poetry
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-v1
        path: |
          ~/.poetry
          .venv

    - name: Cache npm
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-v1
        path: |
          ~/.npm
          node_modules

    - name: Install poetry
      run: |
        pip install poetry
        poetry config virtualenvs.in-project true
    - name: Install poetry dependencies
      run: poetry install

    - name: Install npm dependencies
      run: npm ci

    - name: Build
      run: make publish

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: output/

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
