name: Deploy GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: true
          # 記事の作成日時を取得するため
          fetch-depth: 0
      - uses: ./.github/actions/setup-devenv
        with:
          with-locale: 'true'
      - name: Build
        run: devenv shell make publish
        env:
          LOCALE_ARCHIVE: /usr/lib/locale/locale-archive
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: output/
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
