name: Deploy GitHub Pages

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Enable ja_JP.UTF-8 locale
      run: |
        sudo sed -i 's/# ja_JP\.UTF-8/ja_JP\.UTF-8/' /etc/locale.gen
        sudo update-locale LANG=C.UTF-8 LC_MESSAGES=POSIX
        DEBIAN_FRONTEND=noninteractive sudo -E dpkg-reconfigure locales

    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0

    - uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install stork
      run: |
        sudo wget -O /usr/local/bin/stork https://files.stork-search.net/releases/v1.2.1/stork-ubuntu-latest
        sudo chmod +x /usr/local/bin/stork

    - name: Cache poetry
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-v1
        path: |
          ~/.poetry
          .venv

    - name: Cache npm
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-v1
        path: |
          ~/.npm
          node_modules

    - name: Install poetry
      run: |
        pip install poetry
        poetry config virtualenvs.in-project true
    - name: Install poetry dependencies
      run: poetry install

    - name: Install npm dependencies
      run: npm ci

    - name: Set git config
      run: |
        git config user.name 'release-bot'
        git config user.email 'release-bot@users.noreply.github.com'

    - name: Create gh-pages branch
      run: |
        git fetch origin gh-pages
        git branch --track gh-pages origin/gh-pages

    - name: Deploy to GitHub Pages
      run: make github
