name: Deploy GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Enable ja_JP.UTF-8 locale
        run: |
          sudo sed -i 's/# ja_JP\.UTF-8/ja_JP\.UTF-8/' /etc/locale.gen
          sudo update-locale LANG=C.UTF-8 LC_MESSAGES=POSIX
          DEBIAN_FRONTEND=noninteractive sudo -E dpkg-reconfigure locales
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Cache poetry
        uses: actions/cache@v4
        with:
          key: poetry1-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          path: |
            ~/.poetry
            .venv
      - name: Cache npm
        uses: actions/cache@v4
        with:
          key: npm1-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          path: |
            ~/.npm
            node_modules
      - name: Install by devenv
        run: |
          nix profile install nixpkgs#devenv
          devenv shell echo
      - name: Install Python packages
        run: devenv shell poetry install --no-interaction --no-root
      - name: Install npm packages
        run: devenv shell npm ci
      - name: Build
        run: devenv shell make publish
        env:
          LOCALE_ARCHIVE: /usr/lib/locale/locale-archive
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: output/
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
