name: Deploy GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true
          fetch-depth: 0
      - uses: ./.github/actions/setup-devenv
        with:
          with-locale: 'true'
      - name: Build
        run: devenv shell make publish
        env:
          LOCALE_ARCHIVE: /usr/lib/locale/locale-archive
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: output/
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
